apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myakspvc2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: myaks